NumPy (Numerical Python) is a fundamental package in Python for numerical computations. It provides support for working with arrays, matrices, and various mathematical functions that are essential for scientific and data analysis tasks. NumPy forms the foundation for many other scientific computing libraries in the Python ecosystem.

## importing library

In [1]:
import numpy as np

# Creating a NumPy array

In [2]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
arr2 = np.arange(10, 21)
print(arr2)
arr3 = np.linspace(0,1,5)
print(arr3)

[1 2 3 4 5 6]
[10 11 12 13 14 15 16 17 18 19 20]
[0.   0.25 0.5  0.75 1.  ]


# Indexing and Slicing

In [3]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.arange(10, 21)
print(arr1[2])
print(arr1[3:6])
print(arr2[3:6])

3
[4 5 6]
[13 14 15]


# Array operations

In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,12,13,14,15])
print(arr1.shape)
print(arr2.shape)
arr = arr1 + arr2
print(arr)

(5,)
(5,)
[12 14 16 18 20]


# Reshaping Arrays

In [5]:
arr1 = np.array([1,2,3,4,56,7,8,9])
reshape = arr1.reshape(2,4)
reshape

array([[ 1,  2,  3,  4],
       [56,  7,  8,  9]])

# Array Concatenation

In [6]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
concatenation = np.concatenate((arr1, arr2))
print(concatenation)

[ 1  2  3  4  5  6  7  8  9 10]


# Aggregating Data

In [7]:
arr1 = np.array([1,2,3,4,5,45,67,43])
mean_value = np.mean(arr1)
print(mean_value)

21.25


# Filtering Data

In [8]:
arr1 = np.array([10,20,48,48,284,48,2,6])
filtered = arr1[arr1 >20]
print(filtered)

[ 48  48 284  48]


# Sorting Array

In [9]:
arr1 = np.array([2,5,22,67,43,778,45,33,56,1])
sorted_array = np.sort(arr1)
print(sorted_array)

[  1   2   5  22  33  43  45  56  67 778]


# Unique Values

In [10]:
arr1 = np.array([1,1,1,4,5,3,2,4,555,3,56,75,35,78,532,357,])
unique_value , unique_count = np.unique(arr1, return_counts=True)
print(unique_value)
print(unique_count)

[  1   2   3   4   5  35  56  75  78 357 532 555]
[3 1 2 2 1 1 1 1 1 1 1 1]


# Vectorized Operations

In [11]:
arr1 = np.array([1,2,3,4,5])
myarray = arr1*2
myarray

array([ 2,  4,  6,  8, 10])